@startmindmap
title UML
* UML
**[#lightgreen] 1.用例图：从用户角度描述系统功能，并指明各功能操作者

** 静态图
***[#lightgreen] 2.类图：表示类之间的联系，类的属性和操作，在系统的整个生命周期有效
***[#lightgreen] 3.对象图：是类图的一个实例，标识与类图一致，但生命周期有限，只在某一时间段有效

** 交互图
***[#lightgreen] 4.时序图：消息在对象间的发送顺序
***[#lightgreen] 5.协作图：描述对象间的协作关系，强调上下级关系

** 行为图
***[#lightgreen] 6.活动图：可以用于描述系统的工作流程和并发行为，跟流程图类似但稍有不同
***[#lightgreen] 7.状态图：描述对象的所有状态和状态之间的转换

** 实现图
***[#lightgreen] 8.部署图：用来显示系统中软件和硬件的物理架构
***[#lightgreen] 9.组件图：用来描述组件与组件之间的关系
@endmindmap