@startuml
|开发人员|
start
:在"/开发demo"下新建迭代文件夹;
note left:文件夹以上线日期命名，例：20200709
:把需要修改的页面copy到迭代文件夹。\n需要新增页面时在迭代文件夹新建页面;
note left:修改的文件copy后需要修改路径名：\n原路径名+版本名
:在迭代文件夹开发完成;
:把迭代文件夹下的文件覆盖原有项目文件。\n把新增文件copy到项目正确路径;
note left:注意还原路径名称
:自测完成;
|负责人|
:打包发布;
|测试人员|
:测试通过;
|开发人员|
if (是否有紧急修改) then (有)
    :通知测试人员;
    :在迭代文件夹下修改代码完成;
    :把迭代文件夹下修改过的文件覆盖项目中的文件;
    note left:注意还原路径名称
    :自测完成;
    |负责人|
    :打包发布;
    |测试人员|
    :测试通过;
else (没有)
    |负责人|
    :发布文档;
    stop
endif
|负责人|
:发布文档;

stop
@enduml