@startuml
|开发人员|
start
:基于主干新建迭代版本;
:开发完成;
|负责人|
:合并主干版本;
:打包发布主干;
|测试人员|
:测试通过;
|开发人员|
if (是否有紧急修改) then (有)
    :通知测试人员;
    :修改代码完成;
    |负责人|
    :合并主干版本;
    :打包发布主干;
    |测试人员|
    :测试通过;
else (没有)
    |负责人|
    :发布文档;
    stop
endif
|负责人|
:发布文档;

stop
@enduml