server:
  port: 1002

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9848
#      filter:
#        enabled: false

#指定FeignClientApi的日志级别，不设置为debug不会打印日志
logging:
  level:
    com:
      daliu:
        order:
          api:
            feign: basic

feign:
  client:
    config:
      product-center:
        loggerLevel: basic
        contract: feign.Contract.Default
  httpclient:
    #让feign底层使用HttpClient去调用，这样才会使用连接池，否则的话使用url连接，这时候没用连接池
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connection-timeout: 3000

ribbon:
  connectTimeout: 2000
  readTimeout: 2000

#actuator 暴露所有端口 配置上，就能访问http://127.0.0.1:1002/actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      #
      show-details: always