server:
  port: 1002

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 127.0.0.1:8848

#指定FeignClientApi的日志级别，不设置为debug不会打印日志
logging:
  level:
    com:
      daliu:
        order:
          api:
            feign: debug