server:
  port: 2003

spring:
  application:
    name: credit-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 127.0.0.1:8848
        # 指定集群名称
        cluster-name: NJ
#        metadata:
#          version: v1