server:
  port: 9000

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定集群名称
        cluster-name: BJ
        metadata:
          version: v1

    sentinel:
      transport:
        # 配置sentinel控制台的地址
        dashboard: 127.0.0.1:8080
        #指定和控制台通信的IP
        #如不配置，会自动选择一个IP注册
        client-ip: 127.0.0.1

feign:
  sentinel:
    # 开启Sentinel对Feign的支持
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
